# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.14.2
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: false
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_version: 12.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: 'Includes modules that expand official website modules and include:


    * More functionality for the website builder.

    * More building blocks with pre-configured data (snippets).

    * Tools for the website environment.

    * and more...'
repo_name: Odoo modules for website builder
repo_slug: website
repo_website: https://github.com/OCA/website
travis_apt_packages: []
travis_apt_sources: []

