[project]
name = "odoo-addons-oca-website"
version = "18.0.20250716.0"
dependencies = [
    "odoo-addon-website_cookiefirst==18.0.*",
    "odoo-addon-website_form_require_legal==18.0.*",
    "odoo-addon-website_legal_page==18.0.*",
    "odoo-addon-website_odoo_debranding==18.0.*",
    "odoo-addon-website_product_document_download_counter==18.0.*",
    "odoo-addon-website_snippet_country_dropdown==18.0.*",
    "odoo-addon-website_whatsapp==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
