import setuptools

with open('VERSION.txt', 'r') as f:
    version = f.read().strip()

setuptools.setup(
    name="odoo8-addons-oca-website",
    description="Meta package for oca-website Odoo addons",
    version=version,
    install_requires=[
        'odoo8-addon-website_analytics_piwik',
        'odoo8-addon-website_anchor_smooth_scroll',
        'odoo8-addon-website_backend_views',
        'odoo8-addon-website_blog_excerpt_img',
        'odoo8-addon-website_blog_facebook_comment',
        'odoo8-addon-website_blog_mgmt',
        'odoo8-addon-website_blog_share',
        'odoo8-addon-website_blog_title_image',
        'odoo8-addon-website_breadcrumb',
        'odoo8-addon-website_calendar_snippet',
        'odoo8-addon-website_canonical_url',
        'odoo8-addon-website_container_fluid',
        'odoo8-addon-website_cookie_notice',
        'odoo8-addon-website_country_localized_pages',
        'odoo8-addon-website_crm_address',
        'odoo8-addon-website_crm_privacy_policy',
        'odoo8-addon-website_crm_quick_answer',
        'odoo8-addon-website_crm_recaptcha',
        'odoo8-addon-website_event_filter_organizer',
        'odoo8-addon-website_event_register_free',
        'odoo8-addon-website_event_register_free_with_sale',
        'odoo8-addon-website_form_recaptcha',
        'odoo8-addon-website_hr_contact',
        'odoo8-addon-website_hr_department',
        'odoo8-addon-website_img_bg_style',
        'odoo8-addon-website_legal_page',
        'odoo8-addon-website_logo',
        'odoo8-addon-website_menu_by_user_status',
        'odoo8-addon-website_menu_multilang',
        'odoo8-addon-website_multi_image',
        'odoo8-addon-website_no_crawler',
        'odoo8-addon-website_parameterized_snippet',
        'odoo8-addon-website_portal',
        'odoo8-addon-website_portal_purchase',
        'odoo8-addon-website_portal_sale',
        'odoo8-addon-website_product_supplier',
        'odoo8-addon-website_sale_collapse_categories',
        'odoo8-addon-website_sale_order_company',
        'odoo8-addon-website_sale_product_category_seo',
        'odoo8-addon-website_sale_survey',
        'odoo8-addon-website_sale_unsaleable_options',
        'odoo8-addon-website_sale_vat_required',
        'odoo8-addon-website_seo_redirection',
        'odoo8-addon-website_signup_legal_page_required',
        'odoo8-addon-website_slides',
        'odoo8-addon-website_snippet_anchor',
        'odoo8-addon-website_snippet_big_button',
        'odoo8-addon-website_snippet_contact_form',
        'odoo8-addon-website_snippet_country_dropdown',
        'odoo8-addon-website_snippet_marginless_gallery',
        'odoo8-addon-website_supplier_list',
        'odoo8-addon-website_upload_video',
    ],
    classifiers=[
        'Programming Language :: Python',
        'Framework :: Odoo',
    ]
)
